
FROM node:lts AS builder
WORKDIR /src/
COPY webui/package*.json ./webui/
WORKDIR /src/webui
RUN npm ci
COPY webui .
RUN npm run build-prod
FROM nginx:stable
COPY --from=builder /src/webui/dist /usr/share/nginx/html