openapi: 3.0.3
info:
  title: WASAchat
  description: WASAchat backend REST API
  version: 0.0.1
servers:
- url: http://localhost:5500
components:
  schemas:
    User:
      title: User
      description: "app user"
      type: object
      properties:
        id: 
          description: Unique identifier of a user in the app
          type: integer
          example: 1
          minimum: 0
          readOnly: true
        username: 
          description: Name choose by the user that can represent him in the app
          type: string
          example: samupgn
        profileImage:
          description: Image that represent the user
          format: binary
          type: string
        realName:
          description: Real name of the user
          type: string
          example: Samuele
        realSurname:
          description: Real surname of the user
          type: string
          example: Pagnotta
    Message:
      title: Message
      description: Text or image data sent from a user to another
      type: object
      properties:
        id: 
          description: Unique identifier of a message in the chat
          type: integer
          example: 1 
          readOnly: true
        messageType:
          description: Identifier of the type of the message
          type: string
          enum: ["image", "text"]
          example: text
        content: 
          description: Content of the message
          type: string
          example: |
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
        previewContent: 
          description: content
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit
        sender:
          description: username of the user that have sent the message
          type: string
          example: samupgn
        timestamp:
          description: Unix timestamp of the time when the user sent the message
          type: string
          example: 1731086574
        status: 
          description: Show if the user have received the message or not
          type: string
          enum: [sent, received, not_sent]
          example: sent
        replyTo:
          description: id of the message who this message reply
          type: integer
          minimum: 0
          example: 0
    Chat:
      title: Chat
      description: Conversations between 2 or more users
      type: object
      properties:
        id: 
          description: Unique identifier of the chat from an user
          type: integer
          minimum: 0
          example: 1
        messageList:
          description: Message list in the chat
          type: array
          items:
            $ref: '#/components/schemas/Message'
        partecipantsId:
          description: list of users ID who take part of the chat
          type: array
          items:
            type: integer
            minimum: 0
          example: [0, 1]
        photo: 
          description: Photo of the chat if is a group
          type: string
          format: binary
paths:
  /session:
    post:
      tags: ["User Management"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: integer
                    example: 0
  /user/setUserName:
    put: 
      tags: ["User Management"]
      summary: Change username
      description: Update of the username for this service
      operationId: setMyUserName
      requestBody:
        description: User new username over the last one
        content:
          application/json: 
            schema:
              type: object
              properties:
                newName: 
                  type: string
                  example: Samuele
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        "200":
          description: Username updated successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "400":
          description: Invalid input (e.g. username already used)
        "401":
          description: User have to Auth itself to change username
        "404": 
          description: User not found
  /user/setPhoto:
    post: 
      tags: ["User Management"]
      summary: Change Photo
      description: Update of the Photo of the user for this service
      operationId: setMyPhoto
      requestBody:
        description: User new Photo over the last one
        content:
          application/json: 
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
                  description: The photo file to upload (image)
        required: true
      responses:
        "200":
          description: photo updated successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "400":
          description: Invalid input
        "401":
          description: User have to Auth itself to set a photo
        "404": 
          description: User not found
  /conversations/{conversationId}/addUser:
    post:
      tags: ["Groupchat Management"]
      summary: Add a user to a group chat (Chat)
      description: Adds a user to an existing group chat, which is a conversation with isGroup set to true
      operationId: addToGroup
      parameters:
        - name: conversationId
          in: path
          description: The ID of the group chat (Chat) to add the user to
          schema:
            type: integer
          required: true
      requestBody:
        description: The user details to add to the group chat
        content:
          application/json: 
            schema:
              type: object
              properties:
                userId: 
                  type: integer
                  description: The ID of the user to add to the group chat
        required: true
      responses:
        '200':
          description: User successfully added to the group chat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid input (e.g. invalid user ID)
        "401":
          description: User must authenticate to add someone to a group
        "403":
          description: User does not have permission to add users to this group
        "404":
          description: group chat or user not found
  /conversations/{conversationId}/leave:
    delete:
      tags: ["Groupchat Management"]
      summary: Leave a group chat (Chat)
      description: Allows a user to leave an existing group chat (Chat).
      operationId: leaveGroup
      parameters:
        - name: conversationId
          in: path
          description: The ID of the group chat (Chat) the user is leaving
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: User successfully left the group chat
        "400":
          description: Invalid input (e.g. user not part of the conversation)
        "401":
          description: User must authenticate to leave the group
        #"403": non so se metterla
        #  description: User is not authorized to leave the group
        "404":
          description: Conversation not found or user is not a participant
  /conversations/{conversationId}/setGroupName:
    post: 
      tags: ["Groupchat Management"]
      summary: Setting up or Change group name
      description: Update or setting up the username for this GroupChat (Chat)
      operationId: setGroupName
      parameters:
        - name: conversationId
          in: path
          description: The ID of the group chat (Chat) the user is leaving
          schema:
            type: integer
          required: true
      requestBody:
        description: New GroupChat name 
        content:
          application/json: 
            schema:
              type: object
              properties:
                newName: 
                  type: string
                  example: Informatica
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        "200":
          description: Group name updated successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "400":
          description: Invalid input (e.g. Group name already used)
        "401":
          description: User have to Auth itself to change a Group name
        "404": 
          description: Group (Chat) not found       
  /conversations/{conversationId}/setGroupPhoto:
    post: 
      tags: ["Groupchat Management"]
      summary: Change GroupChat (Chat) Photo
      description: Update of the Photo of the GroupChat (Chat) selected
      operationId: setGroupPhoto
      parameters:
        - name: conversationId
          in: path
          description: The ID of the group chat (Chat) the user is leaving
          schema:
            type: integer
          required: true
      requestBody:
        description: Group new Photo over the last one
        content:
          application/json: 
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
                  description: The photo file to upload (image)
        required: true
      responses:
        "200":
          description: photo updated successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Chat" }
        "400":
          description: Invalid input
        "401":
          description: User have to Auth itself to set a photo
        "404": 
          description: User not found
  /conversations/:
    get:
      tags: ["Conversation Based"]
      summary: Retrieve the list of all the user conversations
      description: Retrieve chronologically reversed all the conversation connected with the user
      operationId: getMyConversations
      responses:
        '200':
          description: list of Conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chat'
        "401":
          description: User have to Auth itself to see the Conversations
  /conversations/{conversationId}:
    get:
      tags: ["Conversation Based"]
      summary: Retrieve a single conversation by ID
      description: Retrieve a specific conversation connected with the user by its ID
      operationId: getConversation
      parameters:
        - name: conversationId
          in: path
          description: The ID of the conversation to retrieve
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Single conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        "401":
          description: User has to authenticate to view the conversation
        "403":
          description: User does not have access rights to the content
        "404":
          description: Conversation not found
  /conversations/{conversationId}/sendMessage:
    post:
      tags: ["Conversation Based"]
      summary: Send a message in a conversation
      description: Send a new message to a specific conversation identified by conversationId
      operationId: sendMessage
      parameters:
        - name: conversationId
          in: path
          description: The ID of the conversation to send the message to
          schema:
            type: integer
          required: true
      requestBody:
        description: The message details to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        "400":
          description: Invalid input
        "401":
          description: User has to authenticate to send the message
        "403":
          description: User does not have access rights to the content
        "404":
          description: Conversation not found
  /conversations/{sourceConversationId}/messages/{messageId}/forward:
    post:
      tags: ["Conversation Based"]
      summary: Forward a message to a different conversation
      description: Forward an existing message to the specified conversation
      operationId: forwardMessage
      parameters:
        - name: sourceConversationId
          in: path
          description: The ID of the conversation where you already have the message
          schema:
            type: integer
          required: true
        - name: messageId
          in: path
          description: The ID of the message to forward
          schema:
            type: integer
          required: true
      requestBody:
        description: Target conversation and additional details for forwarding the message
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                targetConversationId:
                  type: integer
                  description: The ID of the target conversation to which the message is being forwarded
                customContent:
                  type: string
                  description: Optional additional content added when forwarding the message
              required:
                - targetConversationId
      responses:
        '201':
          description: Message forwarded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        "400":
          description: Invalid input
        "401":
          description: User has to authenticate to forward the message
        "403":
          description: User does not have access rights to the content
        "404":
          description: Conversation or message not found
  /conversations/{conversationId}/messages/{messageId}/comment:
    post:
      tags: ["Conversation Based"]
      summary: Add a comment to a message
      description: Adds a comment to a specific message within a conversation
      operationId: commentMessage
      parameters:
      - name: conversationId
        in: path
        description: The ID of the conversation containing the message to comment on
        schema:
          type: integer
        required: true
      - name: messageId
        in: path
        description: The ID of the message to comment on
        schema:
          type: integer
        required: true
      requestBody:
        description: The comment as a Message
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '201':
          description: Comment added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        "400":
          description: Invalid input
        "401":
          description: User must authenticate to add a comment
        "403":
          description: User does not have access rights to the content
        "404":
          description: Conversation or message not found
  /conversations/{conversationId}/messages/{messageId}/uncomment:
    delete:
      tags: ["Conversation Based"]
      summary: Delete a comment from a message
      description: Deletes a specific comment on a message within a conversation
      operationId: uncommentMessage
      parameters:
      - name: conversationId
        in: path
        description: The ID of the conversation containing the message
        schema:
          type: integer
        required: true
      - name: messageId
        in: path
        description: The ID of the message who is a comment
        schema:
          type: integer
        required: true
      responses:
        '204':
          description: Comment deleted successfully
        "400":
          description: Invalid input
        "401":
          description: User must authenticate to delete the comment
        "403":
          description: User is not authorized to delete this comment
        "404":
          description: Conversation or comment not found
  /conversations/{conversationId}/messages/{messageId}/delMessage:
    delete:
      tags: ["Conversation Based"]
      summary: Delete a message from the conversation
      description: Deletes a specific message within a conversation
      operationId: deleteMessage
      parameters:
      - name: conversationId
        in: path
        description: The ID of the conversation containing the message
        schema:
          type: integer
        required: true
      - name: messageId
        in: path
        description: The ID of the message that will be deleted
        schema:
          type: integer
        required: true
      responses:
        '204':
          description: message deleted successfully
        "400":
          description: Invalid input
        "401":
          description: User must authenticate to delete the message
        "403":
          description: User is not authorized to delete this message
        "404":
          description: Conversation or message not found
