openapi: 3.0.3
info:
  title: WASAchat
  description: WASAchat backend REST API
  version: 0.0.1
servers:
- url: http://localhost:5500
components:
  schemas:
    User:
      title: User
      description: "app user"
      type: object
      properties:
        id: 
          description: Unique identifier of a user in the app
          type: integer
          example: 1
          minimum: 0
          readOnly: true
        username: 
          description: Name choose by the user that can represent him in the app
          type: string
          example: samupgn
        profileImage:
          description: Image that represent the user
          type: string
          example: https://www.istockphoto.com/illustrations/placeholder-image
        realName:
          description: Real name of the user
          type: string
          example: Samuele
        realSurname:
          description: Real surname of the user
          type: string
          example: Pagnotta
    Message:
      title: Message
      description: Text or image data sent from a user to another
      type: object
      properties:
        id: 
          description: Unique identifier of a message in the chat
          type: integer
          example: 1 
          readOnly: true
        messageType:
          description: Identifier of the type of the message
          type: string
          enum: ["image", "text"]
          example: text
        content: 
          description: Content of the message
          type: string
          example: |
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
        previewContent: 
          description: content
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit
        sender:
          description: username of the user that have sent the message
          type: string
          example: samupgn
        timestamp:
          description: Unix timestamp of the time when the user sent the message
          type: string
          example: 1731086574
        status: 
          description: Show if the user have received the message or not
          type: string
          enum: [sent, received, not_sent]
          example: sent
        replyTo:
          description: id of the message who this message reply
          type: integer
          minimum: 0
          example: 0
    Chat:
      title: Chat
      description: Conversations between 2 or more users
      type: object
      properties:
        id: 
          description: Unique identifier of the chat from an user
          type: integer
          minimum: 0
          example: 1
        messageList:
          description: Message list in the chat
          type: array
          items:
            $ref: '#/components/schemas/Message'
        partecipantsId:
          description: list of users ID who take part of the chat
          type: array
          items:
            type: integer
            minimum: 0
          example: [0, 1]
        photo: 
          description: Photo of the chat if is a group
          type: string
          example: "https://.."
paths:
  /session:
    post:
      tags: ["User Setting"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
  /setMyUserName:
    post: 
      tags: ["User Setting"]
      summary: Change username
      description: Update of the username for this service
      operationId: setMyUserName
      requestBody:
        description: User new username over the last one
        content:
          application/json: 
            schema:
              type: object
              properties:
                newName: 
                  type: string
                  example: Samuele
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        "200":
          description: Fountain updated successfully
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "404": 
          description: User not found
        "401":
          description: User have to Auth itself to change username
        "403": 
          description: Username already in use
  /conversations/:
    get:
      tags: ["Conversation Based"]
      summary: Retrieve the list of all the user Conversations
      description: Retrieve chronologically reversed all the conversation connected with the user
      operationId: getMyConversations
      responses:
        '200':
          description: list of Conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chat'
        "401":
          description: User have to Auth itself to see the Conversations
  /conversations/{conversationId}:
    get:
      tags: ["Conversation Based"]
      summary: Retrieve a single conversation by ID
      description: Retrieve a specific conversation connected with the user by its ID
      operationId: getConversation
      parameters:
        - name: conversationId
          in: path
          description: The ID of the conversation to retrieve
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Single conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        "401":
          description: User has to authenticate to view the conversation
        "403":
          description: User does not have access rights to the content
        "404":
          description: Conversation not found
  /conversations/{conversationId}/sendMessage:
    post:
      tags: ["Conversation Based"]
      summary: Send a message in a conversation
      description: Send a new message to a specific conversation identified by conversationId
      operationId: sendMessage
      parameters:
        - name: conversationId
          in: path
          description: The ID of the conversation to send the message to
          schema:
            type: integer
          required: true
      requestBody:
        description: The message details to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        "400":
          description: Invalid input
        "401":
          description: User has to authenticate to send the message
        "403":
          description: User does not have access rights to the content
        "404":
          description: Conversation not found
  /conversations/{sourceConversationId}/messages/{messageId}/forward:
    post:
      tags: ["Conversation Based"]
      summary: Forward a message to a different conversation
      description: Forward an existing message to the specified conversation
      operationId: forwardMessage
      parameters:
        - name: sourceConversationId
          in: path
          description: The ID of the conversation where you already have the message
          schema:
            type: integer
          required: true
        - name: messageId
          in: path
          description: The ID of the message to forward
          schema:
            type: integer
          required: true
      requestBody:
        description: Target conversation and additional details for forwarding the message
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                targetConversationId:
                  type: integer
                  description: The ID of the target conversation to which the message is being forwarded
                customContent:
                  type: string
                  description: Optional additional content added when forwarding the message
              required:
                - targetConversationId
      responses:
        '201':
          description: Message forwarded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        "400":
          description: Invalid input
        "401":
          description: User has to authenticate to forward the message
        "403":
          description: User does not have access rights to the content
        "404":
          description: Conversation or message not found
  /conversations/{conversationId}/messages/{messageId}/comment:
    post:
      tags: ["Conversation Based"]
      summary: Add a comment to a message
      description: Adds a comment to a specific message within a conversation
      operationId: commentMessage
      parameters:
      - name: conversationId
        in: path
        description: The ID of the conversation containing the message to comment on
        schema:
          type: integer
        required: true
      - name: messageId
        in: path
        description: The ID of the message to comment on
        schema:
          type: integer
        required: true
      requestBody:
        description: The comment as a Chat
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chat'
      responses:
        '201':
          description: Comment added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        "400":
          description: Invalid input
        "401":
          description: User must authenticate to add a comment
        "403":
          description: User does not have access rights to the content
        "404":
          description: Conversation or message not found