compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

globalFolder: .yarn/global

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux

yarnPath: .yarn/releases/yarn-4.5.0.cjs
